"""cheapestGasStations table

Revision ID: 8c4f83f4a143
Revises: 
Create Date: 2018-06-15 08:59:39.830940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4f83f4a143'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Carburants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Carburants_label'), 'Carburants', ['label'], unique=True)
    op.create_table('GasStations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('zipCode', sa.String(length=5), nullable=False),
    sa.Column('type', sa.String(length=1), nullable=False),
    sa.Column('open', sa.String(length=5), nullable=False),
    sa.Column('close', sa.String(length=5), nullable=False),
    sa.Column('closingDays', sa.String(length=20), nullable=True),
    sa.Column('services', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GasStations_latitude'), 'GasStations', ['latitude'], unique=False)
    op.create_index(op.f('ix_GasStations_longitude'), 'GasStations', ['longitude'], unique=False)
    op.create_table('Services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Services_label'), 'Services', ['label'], unique=True)
    op.create_table('GasStationCarburantData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gasStationId', sa.Integer(), nullable=True),
    sa.Column('carburantId', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('lastUpdate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['carburantId'], ['Carburants.id'], ),
    sa.ForeignKeyConstraint(['gasStationId'], ['GasStations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GasStationCarburantData_carburantId'), 'GasStationCarburantData', ['carburantId'], unique=False)
    op.create_index(op.f('ix_GasStationCarburantData_gasStationId'), 'GasStationCarburantData', ['gasStationId'], unique=False)
    op.create_index(op.f('ix_GasStationCarburantData_lastUpdate'), 'GasStationCarburantData', ['lastUpdate'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_GasStationCarburantData_lastUpdate'), table_name='GasStationCarburantData')
    op.drop_index(op.f('ix_GasStationCarburantData_gasStationId'), table_name='GasStationCarburantData')
    op.drop_index(op.f('ix_GasStationCarburantData_carburantId'), table_name='GasStationCarburantData')
    op.drop_table('GasStationCarburantData')
    op.drop_index(op.f('ix_Services_label'), table_name='Services')
    op.drop_table('Services')
    op.drop_index(op.f('ix_GasStations_longitude'), table_name='GasStations')
    op.drop_index(op.f('ix_GasStations_latitude'), table_name='GasStations')
    op.drop_table('GasStations')
    op.drop_index(op.f('ix_Carburants_label'), table_name='Carburants')
    op.drop_table('Carburants')
    # ### end Alembic commands ###
